# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1442115877);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1442115997);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1443065514);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1443219431);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1443216591);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 29);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150629114848");
user_pref("browser.slowStartup.averageTime", 16233);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20150629114848");
user_pref("browser.startup.homepage_override.mstone", "39.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1443216539197");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1443216541115");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1443302941115");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1442115395253");
user_pref("datareporting.policy.firstRunTime", "1442115326971");
user_pref("datareporting.sessions.current.activeTicks", 10);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 15941);
user_pref("datareporting.sessions.current.main", 51);
user_pref("datareporting.sessions.current.sessionRestored", 17242);
user_pref("datareporting.sessions.current.startTime", "1443219297975");
user_pref("datareporting.sessions.current.totalTime", 155);
user_pref("datareporting.sessions.currentIndex", 10);
user_pref("datareporting.sessions.previous.7", "{\"s\":1443216463349,\"a\":4,\"t\":104,\"c\":false,\"m\":42,\"fp\":13715,\"sr\":13813}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1443216740518,\"a\":1,\"t\":42,\"c\":false,\"m\":42,\"fp\":13813,\"sr\":14562}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1443218230490,\"a\":2,\"t\":44,\"c\":false,\"m\":41,\"fp\":15137,\"sr\":16212}");
user_pref("datareporting.sessions.prunedIndex", 6);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"39.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"39.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:39.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1442115878);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "39.0");
user_pref("extensions.lastPlatformVersion", "39.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"39.0\",\"st\":1438804188000,\"mt\":1435579394000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"39.0\",\"st\":1435580049000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"39.0\",\"st\":1435580049000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1438804318000,\"mt\":1420839872000}}}");
user_pref("gecko.buildID", "20150629114848");
user_pref("gecko.mstone", "39.0");
user_pref("idle.lastDailyNotification", 1443216620);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1442115453);
user_pref("media.gmp-gmpopenh264.version", "1.4");
user_pref("media.gmp-manager.buildID", "20150629114848");
user_pref("media.gmp-manager.lastCheck", 1443216536);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1442115980);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1442115980);
user_pref("toolkit.startup.last_success", 1443219298);
user_pref("toolkit.telemetry.previousBuildID", "20150629114848");
